name: BankGB
author: Biswajit
api: 5.0.0
version: 1.1.0
main: Biswajit\BankGB\BankGB

commands:
  bank:
    description: "Bank Command"
    permission: "BankGB.bank.cmd"
  setbankmoney:
    description: "setbankmoney Command"
    permission: "BankGB.setbankmoney.cmd"
    
permissions:
  BankGB.bank.cmd:
    description: "Bank Permission"
    default: true
  BankGB.setbankmoney.cmd:
    description: "setbankmoney Permission"
    default: op￼Enter
