---
main: Biswajit\BankGB\BankGB
name: BankGB
version: 1.2.0
api:
- 5.0.0
Author: Biswajit
depend:
- EconomyAPI
commands:
  bank:
    description: Bank Permission
    permission: bankgb.bank.cmd
permissions:
  bankgb.bank.cmd:
    description: Permission to view other players transactions
    default: true
...
